### ISSUE TITLE
Add CS2 Support

### ISSUE THREAD

**Issue by NyanCatIsNear** [CoryZ40/Kitten-for-CSGO#67]

**Comment by CorySanin** [comment]
As a temporary solution, saving [gamestate_integration_kitten.cfg](https://musickitten.net/gamestate_integration_kitten.cfg) to `steamapps/common/Counter-Strike Global Offensive/game/csgo/cfg/` makes it work just as it did before.

**Comment by NyanCatIsNear** [comment]
It works ! Thanks !
