### ISSUE TITLE
Something about static-cs2-portraits

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [CoryZ40/Kitten-for-CSGO#68]
I'm sorry to contact you here about the issue of static avatars, but you have already archived a project related to static avatars in your other project, so I can only inquire about this topic here.

So my question is  how to use command to disable the dynamic avatar at cs2 ? Trust me, I have searched all the websites or forums where I can access CS2 commands, but there is no answer to using commands to disable this feature because I want to include these commands in my personal cfg, so I am very eager to obtain these commands that can disable dynamic avatars.

I would be very grateful if I could receive your answer.🥰

**Comment by CorySanin** [comment]
`cl_allow_animated_avatars false`
